In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame

rank = {
    "name":   ["Liam", "Olivia", "Noah", "Emma", "Oliver", "Ava", "Elijah", "Sophia"],
    "age":    [25,  29,     22,    28,    33,      27,    24,      31],
    "gender": ["Male","Female","Male","Female","Male","Female","Male","Female"],
    "rank": [1,2,3,4,5,6,7,8]
}

rank_df = DataFrame(rank)
rank_df

     name  age  gender  rank
0    Liam   25    Male     1
1  Olivia   29  Female     2
2    Noah   22    Male     3
3    Emma   28  Female     4
4  Oliver   33    Male     5
5     Ava   27  Female     6
6  Elijah   24    Male     7
7  Sophia   31  Female     8

In [2]:
# fetch out rows based on Null value of specific column
nullAge_df = pd.isnull(rank_df["age"])
rank_df[nullAge_df]

Empty DataFrame
Columns: [name, age, gender, rank]
Index: []